-- https://rosalind.info/problems/mrna/

f 'A' = 4
f 'C' = 2
f 'D' = 2
f 'E' = 2
f 'F' = 2
f 'G' = 4
f 'H' = 2
f 'I' = 3
f 'K' = 2
f 'L' = 6
f 'M' = 1
f 'N' = 2
f 'P' = 4
f 'Q' = 2
f 'R' = 6
f 'S' = 6
f 'T' = 4
f 'V' = 4
f 'W' = 1
f 'Y' = 2

input = "MWFWGPGRQNNAHIIHSKMKTTPIYQISFYKTHYPVAQMNECVYMNPWDPPADTEMNCKNYHKEMLYELIGKLMQVYFRKMSNMPGLPFLFLIFCDVNWFDGCLFRCVLHDMFPTWCPTAKFWNGHNTLYYGALCFAVLSNRKVIMHLDWNNASHRHAYDCEYYPGVDTVCPANSHEHDMDTTRGTVNQVIRYFGETFWFSKFCTVCTRPHVPELAKTYHPASAASWSSRIGDSRWDVTQVAAISGLKTSWPKHICINHVTDWRWDRQTTQWEAPWDPAGAMIHVKHKDCGYVKALGQVLVFNKPYLSNGKRDQDTWLYWWIFWERCPNFLCVCFKRRPPFQRDKIPATISVARYNCGYRPYHAVYLAHEGRCILVPTATAINLNEPNECILLSVSGGWPWQLGLTDNIHTLMTMRNFIRVEFPWEFCMRFQVTPNIDGDWDVKVDEWTKIHPSQSFPSNEHRDDALCTSQNYFMAELSWRHPLKWYCCWAHADEVFYVERAHIDGAPKSIYYDIVTAVLQEMSTRSIINTEFKNARVTSGYGKCDPKEHIFGTIGDCPMIGELCADIDLRIFNCIENPHNNMACCQFHDHTFWFLIQNNQDCLVTNAMLYDGWWTWAFDWWYWVMSFHPSVIVLQLSHTIRCSTDNSDFWKRLSPNYIQSLKGENQQHNVHARISYILSAFDQRMMRDNCMRMPCYYNRWQQDEMRPLQIFFRPLHRWMQHTMGQGEVIFWSTITTHSMDAQNAVDGSFRRYYFCKIITRCTPTRKLMYSNFADRMNEVIDACLKNDEDNQADNSYEVQCDKYGDANVPYGLQAQLHINMIYCPFIPWKGTCTRDWNIGGSRGSCSPAQADPRVERFTGWSTVHNETIEQKRENEGCQKQVCKMNDWRPHIWSVVWPAEMVTMYPEFQMHFMVSFIMCRHNCLAPCGSGFQMYIMWMEGWPIHNRNFCQASPGSVRWAEHSMIPSNQTVACNDHYFLGNYTVYAPWQVYGELGSCN"

main = print $ foldl (\x y -> mod (x * y) 1_000_000) 3 $ map f input
